// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.edu.pk.biuropodrozy.domain;

import pl.edu.pk.biuropodrozy.domain.Customer;

privileged aspect Customer_Roo_JavaBean {
    
    public String Customer.getLogin() {
        return this.login;
    }
    
    public void Customer.setLogin(String login) {
        this.login = login;
    }
    
}
