// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.edu.pk.biuropodrozy.domain;

import javax.persistence.Entity;
import pl.edu.pk.biuropodrozy.domain.Guest;

privileged aspect Guest_Roo_Jpa_Entity {
    
    declare @type: Guest: @Entity;
    
}
